name: aircolis
description: Aircolis

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.0.1+16

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  http: ^0.13.5
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.2.2
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  firebase_messaging: ^14.3.0
  flutter_svg: ^1.0.3
  lottie: ^1.4.2
  flutter_local_notifications: ^12.0.4
  geolocator: ^11.0.0
  modal_bottom_sheet: ^2.0.1
  flutter_map: ^2.2.0
  google_sign_in: ^5.4.3
  intl_phone_field: ^3.2.0
  image_picker: ^0.8.6+1
  url_launcher: ^6.1.8
  shared_preferences: ^2.0.17
  provider: ^6.1.2
  firebase_remote_config: ^3.0.15
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.2
  share: ^2.0.4
  flutter_countdown_timer: ^4.1.0
  file_picker: ^4.6.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/icons/
    - lang/en.json
    - lang/fr.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
