name: aircolis
description: Aircolis

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.1
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.1
  firebase_messaging: ^9.1.0
  flutter_svg: ^0.19.3
  ff_navigation_bar: ^0.1.5
  lottie: ^0.7.0+1
  flutter_local_notifications: ^5.0.0
  geolocator: ^7.0.1
  geocoder: ^0.2.1
  modal_bottom_sheet: ^2.0.0
  flutter_map: ^0.12.0
  sms_autofill: ^1.3.1
  google_sign_in: ^4.5.1
  intl_phone_field: ^1.4.4
  dotted_border: ^1.0.7
  image_picker: ^0.7.4
  url_launcher: ^6.0.3
  shared_preferences: ^2.0.5
  in_app_purchase: ^0.3.5+1
  # qonversion_flutter: ^2.5.1
  # flutter_otp: ^0.3.2
  provider: ^4.3.1
  firebase_remote_config: ^0.9.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/icons/
    - lang/en.json
    - lang/fr.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic