name: aircolis
description: Aircolis

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.1
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_storage: ^8.0.1
  firebase_messaging: ^10.0.0
  flutter_svg: ^0.22.0
  ff_navigation_bar: ^0.1.5
  lottie: ^1.0.1
  flutter_local_notifications: ^6.0.0
  geolocator: ^7.0.1
  geocoder: ^0.2.1
  modal_bottom_sheet: ^2.0.0
  flutter_map: ^0.13.0
  sms_autofill: ^2.0.0
  google_sign_in: ^5.0.4
  intl_phone_field: ^2.0.0
  #dotted_border: ^2.0.0
  image_picker: ^0.8.0+1
  url_launcher: ^6.0.3
  shared_preferences: ^2.0.5
  in_app_purchase: ^0.3.5+1
  provider: ^4.3.1
  firebase_remote_config: ^0.10.0+1
  apple_sign_in: ^0.1.0
  share:
  flutter_countdown_timer: ^4.1.0
  flutter_swiper: ^1.1.6
  file_picker: ^3.0.1
  #square_in_app_payments: ^1.7.1
  flutter_rating_bar: ^4.0.0
  flutter_braintree: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/icons/
    - lang/en.json
    - lang/fr.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
